
    
esphome:
  name: ld2410 #自己設定name
  platform: ESP32  
  board: esp32doit-devkit-v1 #這邊是設定自己使用的晶片


wifi:
  ssid: "MTK_CHEETAH_AP_2.4G"
  password: "1234567890"
  
  ap:
    ssid: "ESP32-LD2410" #這邊是設置ap，如果沒有連線成功的話

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


# Example configuration entry
uart:
  id: uart99
  tx_pin: GPIO13
  rx_pin: GPIO14
  baud_rate: 256000
  parity: NONE
  stop_bits: 1


sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
