name: build-process
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: esphome/build-action@v2.0.0
      id: esphome-build
      with:
        yaml_file: .github/esphome-web-adcb70.yaml
