name: build-process
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v3
    - uses: esphome/build-action@v1.5.2
      id: esphome-build
      with:
        yaml_file: .github/esp32.yml
